AnalysisType: rule
DedupPeriodMinutes: 60
Description: >-
  Detects when Tines SSO settings are changed
DisplayName: "Tines SSO Settings"
Enabled: true
Filename: tines_sso_settings.py
LogTypes:
  - Tines.Audit
Reference: https://www.tines.com/docs/admin/single-sign-on
RuleID: "Tines.SSO.Settings"
Severity: High
SummaryAttributes:
  - user_id
  - operation_name
  - tenant_id
  - request_ip
Tags:
  - Tines
  - IAM - Credential Security
Tests:
  - ExpectedResult: true
    Log:
      "created_at": "2023-05-16 23:26:46"
      "id": 1111111
      "inputs":
        "domainId": "REDACTED"
        "fingerprint": "REDACTED"
        "idpCertificate": "REDACTED"
        "targetUrl": "REDACTED"
      "operation_name": "SsoConfigurationSamlSet"
      "request_ip": "12.12.12.12"
      "request_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
        (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
      "tenant_id": "8888"
      "user_email": "user@company.com"
      "user_id": "17171"
      "user_name": "user at company dot com"
    Name: Tines SsoConfigurationSamlSet
  - ExpectedResult: false
    Log:
      "created_at": "2023-05-17 14:45:19"
      "id": 7888888
      "operation_name": "Login"
      "request_ip": "12.12.12.12"
      "request_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
        (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
      "tenant_id": "8888"
      "user_email": "user@company.com"
      "user_id": "17171"
      "user_name": "user at company dot com"
    Name: Tines Login
Threshold: 1
