AnalysisType: rule
Filename: aws_config_service_modified.py
PolicyID: AWS.CloudTrail.ConfigServiceModified
DisplayName: AWS Config Service Modified
Enabled: true
ResourceTypes:
  - AWS.CloudTrail
Tags:
  - AWS
  - CIS
  - CIS 3.9
Severity: High
Description: >
  An AWS Config Recorder or Delivery Channel was stopped, deleted, or modified.
Runbook: >
  Verify that the Config Service changes were authorized. If not, revert them and investigate who caused the change. Consider altering permissions to prevent this from happening again in the future.
Reference: https://aws.amazon.com/config/
Tests:
  -
    Name: Config Recorder Stopped
    ResourceType: AWS.CloudTrail
    ExpectedResult: true
    Resource:
      {
          "eventVersion": "1.05",
          "userIdentity": {
              "type": "AssumedRole",
              "principalId": "1111:tester",
              "arn": "arn:aws:sts::123456789012:assumed-role/tester",
              "accountId": "123456789012",
              "accessKeyId": "1",
              "sessionContext": {
                  "sessionIssuer": {
                      "type": "Role",
                      "principalId": "1111",
                      "arn": "arn:aws:iam::123456789012:role/tester",
                      "accountId": "123456789012",
                      "userName": "tester"
                  },
                  "webIdFederationData": {},
                  "attributes": {
                      "mfaAuthenticated": "true",
                      "creationDate": "2019-01-01T00:00:00Z"
                  }
              }
          },
          "eventTime": "2019-01-01T00:00:00Z",
          "eventSource": "config.amazonaws.com",
          "eventName": "StopConfigurationRecorder",
          "awsRegion": "us-west-2",
          "sourceIPAddress": "111.111.111.111",
          "userAgent": "console.amazonaws.com",
          "requestParameters": {
              "configurationRecorderName": "default"
          },
          "responseElements": null,
          "requestID": "1",
          "eventID": "1",
          "eventType": "AwsApiCall",
          "recipientAccountId": "123456789012"
      }
  -
    Name: Config Recorder Started
    ResourceType: AWS.CloudTrail
    ExpectedResult: false
    Resource:
      {
          "eventVersion": "1.05",
          "userIdentity": {
              "type": "AssumedRole",
              "principalId": "1111:tester",
              "arn": "arn:aws:sts::123456789012:assumed-role/tester",
              "accountId": "123456789012",
              "accessKeyId": "1",
              "sessionContext": {
                  "sessionIssuer": {
                      "type": "Role",
                      "principalId": "1111",
                      "arn": "arn:aws:iam::123456789012:role/tester",
                      "accountId": "123456789012",
                      "userName": "tester"
                  },
                  "webIdFederationData": {},
                  "attributes": {
                      "mfaAuthenticated": "true",
                      "creationDate": "2019-01-01T00:00:00Z"
                  }
              }
          },
          "eventTime": "2019-01-01T00:00:00Z",
          "eventSource": "config.amazonaws.com",
          "eventName": "StartConfigurationRecorder",
          "awsRegion": "us-west-2",
          "sourceIPAddress": "111.111.111.111",
          "userAgent": "console.amazonaws.com",
          "requestParameters": {
              "configurationRecorderName": "default"
          },
          "responseElements": null,
          "requestID": "1",
          "eventID": "1",
          "eventType": "AwsApiCall",
          "recipientAccountId": "123456789012"
      }
