AnalysisType: policy
Description: >-
  You can have AWS Config record supported types of global resources, such as IAM
  users, groups, roles, and customer managed policies.
DisplayName: "AWS Config Global Resources"
Enabled: true
Filename: aws_config_global_resources.py
PolicyID: "AWS.Config.GlobalResources"
Reference: https://amzn.to/2MO8xXM
ResourceTypes:
  - AWS.Config.Recorder.Meta
Runbook: >-
  https://docs.runpanther.io/alert-runbooks/built-in-policies/aws-config-is-enabled-for-global-resources
Severity: Low
Tags:
  - AWS
  - Security Control
Tests:
  - ExpectedResult: false
    Name: No Global Recoders Present
    Resource:
      "AccountId": "123456789012"
      "GlobalRecorderCount": 0
      "Name": "AWS.Config.Recorder.Meta"
      "Recorders":
      "Region": "global"
      "ResourceId": "123456789012::AWS.Config.Recorder.Meta"
      "ResourceType": "AWS.Config.Recorder.Meta"
      "Tags":
      "TimeCreated":
  - ExpectedResult: true
    Mocks:
      - objectName: resource_lookup
        returnValue: '{ "AccountId": "012345678910", "Name": "Default", "RecordingGroup":
          { "AllSupported": true, "IncludeGlobalResourceTypes": true, "ResourceTypes":
          null }, "Region": "us-east-1", "ResourceId": "012345678910:us-east-1:AWS.Config.Recorder",
          "ResourceType": "AWS.Config.Recorder", "RoleARN": "arn:aws:iam::012345678910:role/PantherAWSConfig",
          "Status": { "LastErrorCode": null, "LastErrorMessage": null, "LastStartTime":
          "2018-10-05T22:45:01.838Z", "LastStatus": "SUCCESS", "LastStatusChangeTime":
          "2021-05-28T17:45:14.916Z", "LastStopTime": null, "Name": "Default", "Recording":
          true }, "Tags": null, "TimeCreated": null }'
    Name: Global Resources Are Enabled
    Resource:
      "AccountId": "123456789012"
      "GlobalRecorderCount": 4
      "Name": "AWS.Config.Recorder.Meta"
      "Recorders":
        - "123456789012:us-east-1:AWS.Config.Recorder"
        - "123456789012:us-east-2:AWS.Config.Recorder"
        - "123456789012:us-west-1:AWS.Config.Recorder"
        - "123456789012:us-west-2:AWS.Config.Recorder"
      "Region": "global"
      "ResourceId": "123456789012::AWS.Config.Recorder.Meta"
      "ResourceType": "AWS.Config.Recorder.Meta"
      "Tags":
      "TimeCreated":
  - ExpectedResult: false
    Mocks:
      - objectName: resource_lookup
        returnValue: '{"AccountId":"012345678910","Name":"Default","RecordingGroup":{"AllSupported":true,"IncludeGlobalResourceTypes":true,"ResourceTypes":null},"Region":"us-east-1","ResourceId":"012345678910:us-east-1:AWS.Config.Recorder","ResourceType":"AWS.Config.Recorder","RoleARN":"arn:aws:iam::012345678910:role/PantherAWSConfig","Status":{"LastErrorCode":null,"LastErrorMessage":null,"LastStartTime":"2018-10-05T22:45:01.838Z","LastStatus":"SUCCESS","LastStatusChangeTime":"2021-05-28T17:45:14.916Z","LastStopTime":null,"Name":"Default","Recording":false},"Tags":null,"TimeCreated":null}'
    Name: Global Recorders Present - None Recording Global Resources
    Resource:
      "AccountId": "123456789012"
      "GlobalRecorderCount": 1
      "Name": "AWS.Config.Recorder.Meta"
      "Recorders":
        - "123456789012:us-west-2:AWS.Config.Recorder"
      "Region": "global"
      "ResourceId": "123456789012::AWS.Config.Recorder.Meta"
      "ResourceType": "AWS.Config.Recorder.Meta"
      "Tags":
      "TimeCreated":
