AnalysisType: policy
Description: >-
  This policy ensures that the config recorder is operational and capturing changes
  to your account.
DisplayName: "AWS Config Status"
Enabled: true
Filename: aws_config_recording_enabled.py
PolicyID: "AWS.Config.RecordingEnabled"
Reference: 
  https://docs.aws.amazon.com/config/latest/developerguide/stop-start-recorder.html
ResourceTypes:
  - AWS.Config.Recorder
Runbook: >-
  Enable AWS Config recording
Severity: High
Tags:
  - AWS
  - Panther
Tests:
  - ExpectedResult: true
    Name: Recording Enabled
    Resource:
      "Recorder":
        "Name": "default"
        "RecordingGroup":
          "AllSupported": true
          "IncludeGlobalResourceTypes": true
          "ResourceTypes": []
        "RoleARN": "arn:aws:iam::112233445566:role/role-name"
      "Region": "us-west-2"
      "Status":
        "LastErrorCode":
        "LastErrorMessage":
        "LastStartTime": "2019-01-01T00:00:00Z"
        "LastStatus": "SUCCESS"
        "LastStatusChangeTime": "2019-01-01T00:00:00Z"
        "LastStopTime":
        "Name": "default"
        "Recording": true
  - ExpectedResult: false
    Name: Recording Disabled
    Resource:
      "Recorder":
        "Name": "default"
        "RecordingGroup":
          "AllSupported": false
          "IncludeGlobalResourceTypes": true
          "ResourceTypes": []
        "RoleARN": "arn:aws:iam::112233445566:role/role-name"
      "Region": "us-west-2"
      "Status":
        "LastErrorCode":
        "LastErrorMessage":
        "LastStartTime": "2019-01-01T00:00:00Z"
        "LastStatus": "SUCCESS"
        "LastStatusChangeTime": "2019-01-01T00:00:00Z"
        "LastStopTime":
        "Name": "default"
        "Recording": false
