parameters:
  - name: vmImage
    type: string
    default: 'ubuntu-latest'
  - name: poolName
    type: string
    default: ''
  - name: pythonVersion # Parameter to get Python version from main pipeline
    type: string
    default: '3.x'
stages:
  - stage: Unit_Test
    displayName: 'Test Code'
    dependsOn: Validate
    jobs:
      - job: TestAuthenticated
        displayName: 'Test '
        condition: ne(variables['System.PullRequest.IsFork'], 'True') # For internal PRs and direct pushes
        pool:
          ${{ if ne(parameters.poolName, '') }}:
            name: ${{ parameters.poolName }}
          vmImage: ${{ parameters.vmImage }}
        steps:
          - checkout: self
            displayName: 'Checkout repository'
          - script: |
              pip install pipenv
            displayName: 'Install pipenv'
          - script: |
              make venv
            displayName: 'Setup virtual environment'
          - script: |
              if [ -z "$(API_HOST)" ] || [ -z "$(API_TOKEN)" ]; then
                echo "API_HOST or API_TOKEN not set, skipping authenticated tests."
                # You might want to fail the job here if these variables are truly required for authenticated tests
                exit 0 # Exit 0 to pass the job if API_HOST/TOKEN are optional
              fi
              pipenv run panther_analysis_tool test --path ./cws/rules/ --api-host $(API_HOST) --api-token $(API_TOKEN) --show-failures-only
            displayName: 'Run tests'
            env:
              API_HOST: $(API_HOST)
              API_TOKEN: $(API_TOKEN)
