AnalysisType: policy
Description: >-
  This policy validates that AWS Security Groups don't allow unrestricted inbound
  traffic on port 3389 or 22, ports commonly used for the remote access protocols
  RDP and SSH respectively.
DisplayName: "AWS Security Group Administrative Ingress"
Enabled: true
Filename: aws_security_group_administrative_ingress.py
PolicyID: "AWS.SecurityGroup.AdministrativeIngress"
Reference: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html
Reports:
  CIS:
    - 4.1
    - 4.2
  MITRE ATT&CK:
    - TA0001:T1190
ResourceTypes:
  - AWS.EC2.SecurityGroup
Runbook: >-
  https://docs.runpanther.io/alert-runbooks/built-in-policies/aws-securitygroup-restricts-ingress-on-administrative-ports
Severity: High
Tags:
  - AWS
  - Security Control
  - Initial Access:Exploit Public-Facing Application
Tests:
  - ExpectedResult: true
    Name: Inbound IP Permission On All IPs On Acceptable Ports
    Resource:
      "Description": "default VPC security group"
      "GroupId": "sg-abc123"
      "GroupName": "default"
      "IpPermissions":
        - "FromPort": 30
          "IpProtocol": "-1"
          "IpRanges":
            - "CidrIp": "0.0.0.0/0"
              "Description":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort": 45
          "UserIdGroupPairs":
            - "Description":
              "GroupId": "sg-abc123"
              "GroupName":
              "PeeringStatus":
              "UserId": "1122334455"
              "VpcId":
              "VpcPeeringConnectionId":
      "IpPermissionsEgress":
        - "FromPort":
          "IpProtocol": "-1"
          "IpRanges":
            - "CidrIp": "0.0.0.0/0"
              "Description":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort":
          "UserIdGroupPairs":
      "OwnerId": "112233445566"
      "Tags":
      "VpcId": "vpc-123454321"
  - ExpectedResult: false
    Name: Inbound IP Permissions On All IPs On Restricted Ports
    Resource:
      "Description": "default VPC security group"
      "GroupId": "sg-abc123"
      "GroupName": "default"
      "IpPermissions":
        - "FromPort": 22
          "IpProtocol": "-1"
          "IpRanges":
            - "CidrIp": "0.0.0.0/0"
              "Description":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort": 22
          "UserIdGroupPairs":
            - "Description":
              "GroupId": "sg-abc123"
              "GroupName":
              "PeeringStatus":
              "UserId": "1122334455"
              "VpcId":
              "VpcPeeringConnectionId":
      "IpPermissionsEgress":
        - "FromPort":
          "IpProtocol": "-1"
          "IpRanges":
            - "CidrIp": "0.0.0.0/0"
              "Description":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort":
          "UserIdGroupPairs":
      "OwnerId": "112233445566"
      "Tags":
      "VpcId": "vpc-123454321"
  - ExpectedResult: false
    Name: Inbound IP Permission On All IPv6 On Restricted Ports
    Resource:
      "Description": "default VPC security group"
      "GroupId": "sg-abc123"
      "GroupName": "default"
      "IpPermissions":
        - "FromPort": 22
          "IpProtocol": "-1"
          "IpRanges":
          "Ipv6Ranges":
            - "CidrIpv6": "::/0"
              "Description":
          "PrefixListIds":
          "ToPort": 22
          "UserIdGroupPairs":
            - "Description":
              "GroupId": "sg-abc123"
              "GroupName":
              "PeeringStatus":
              "UserId": "1122334455"
              "VpcId":
              "VpcPeeringConnectionId":
      "IpPermissionsEgress":
        - "FromPort":
          "IpProtocol": "-1"
          "IpRanges":
            - "CidrIp": "0.0.0.0/0"
              "Description":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort":
          "UserIdGroupPairs":
      "OwnerId": "112233445566"
      "Tags":
      "VpcId": "vpc-123454321"
  - ExpectedResult: true
    Name: Inbound IP Permission On Specific IP On Restricted Port
    Resource:
      "Description": "default VPC security group"
      "GroupId": "sg-abc123"
      "GroupName": "default"
      "IpPermissions":
        - "FromPort": 22
          "IpProtocol": "-1"
          "IpRanges":
            - "CidrIp": "1.1.1.1/32"
              "Description":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort": 22
          "UserIdGroupPairs":
            - "Description":
              "GroupId": "sg-abc123"
              "GroupName":
              "PeeringStatus":
              "UserId": "1122334455"
              "VpcId":
              "VpcPeeringConnectionId":
      "IpPermissionsEgress":
        - "FromPort":
          "IpProtocol": "-1"
          "IpRanges":
            - "CidrIp": "0.0.0.0/0"
              "Description":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort":
          "UserIdGroupPairs":
      "OwnerId": "112233445566"
      "Tags":
      "VpcId": "vpc-123454321"
  - ExpectedResult: true
    Name: No Inbound IP Permissions
    Resource:
      "Description": "default VPC security group"
      "GroupId": "sg-abc123"
      "GroupName": "default"
      "IpPermissions":
        - "FromPort":
          "IpProtocol": "-1"
          "IpRanges":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort":
          "UserIdGroupPairs":
            - "Description":
              "GroupId": "sg-abc123"
              "GroupName":
              "PeeringStatus":
              "UserId": "1122334455"
              "VpcId":
              "VpcPeeringConnectionId":
      "IpPermissionsEgress":
        - "FromPort":
          "IpProtocol": "-1"
          "IpRanges":
            - "CidrIp": "0.0.0.0/0"
              "Description":
          "Ipv6Ranges":
          "PrefixListIds":
          "ToPort":
          "UserIdGroupPairs":
      "OwnerId": "112233445566"
      "Tags":
      "VpcId": "vpc-123454321"
