AnalysisType: rule
Description: Deployment deleted in Vercel.
DisplayName: "Vercel: Deployment Deleted"
Enabled: true
Filename: deployment_deletion.py
Severity: Medium
DedupPeriodMinutes: 60
Threshold: 1
LogTypes:
  - Vercel.Log
RuleID: "Vercel.Deployment.DeploymentDeletion"
