AnalysisType: rule
Description: Vercel edge configurations modified.
DisplayName: "Vercel: Edge Config Changed"
Enabled: true
Filename: edge_config.py
Severity: Medium
DedupPeriodMinutes: 60
Threshold: 1
LogTypes:
  - Vercel.Log
RuleID: "Vercel.Audit.EdgeConfig"
