AnalysisType: policy
Description: >-
  Verifies that the S3 Bucket Object Lifecycle configuration expires data within 90
  and 365 days.
DisplayName: "AWS S3 Bucket Lifecycle Configuration"
Enabled: true
Filename: aws_s3_bucket_lifecycle_configuration.py
PolicyID: "AWS.S3.Bucket.LifecycleConfiguration"
Reference: https://amzn.to/2visoXr
Reports:
  PCI:
    - 3.1
    - 10.7
ResourceTypes:
  - AWS.S3.Bucket
Runbook: >-
  https://docs.runpanther.io/alert-runbooks/built-in-policies/aws-s3-bucket-lifecycle-configuration-expires-data
Severity: Low
Tags:
  - AWS
  - Configuration Required
  - Security Control
Tests:
  - ExpectedResult: true
    Name: Bucket Has a Compliant 1-Year Lifecycle Configuration
    Resource:
      "CreationDate": "2019-01-01T00:00:00Z"
      "EncryptionRules":
        - "ApplyServerSideEncryptionByDefault":
            "KMSMasterKeyID":
            "SSEAlgorithm": "AES256"
      "Grants":
      "LifecycleRules":
        - "AbortIncompleteMultipartUpload":
          "Expiration":
            "Date":
            "Days": 365
            "ExpiredObjectDeleteMarker":
          "Filter":
            "And":
            "Prefix": ""
            "Tag":
          "ID": "ExpireAfter1Year"
          "NoncurrentVersionExpiration":
            "NoncurrentDays": 365
          "NoncurrentVersionTransitions":
          "Prefix":
          "Status": "Enabled"
          "Transitions":
      "Location": "us-east-2"
      "LoggingPolicy":
      "MFADelete":
      "Name": "bucket-name"
      "Owner":
        "DisplayName": "user.name"
        "ID": "11112223334445556667778899aaabbbcccdddeeee"
      "Policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\"\
        ,\"Principal\":{\"AWS\":\"arn:aws:iam::123456789012:root\"},\"Action\":[\"\
        s3:ListBucket\",\"s3:PutObject\"],\"Resource\":[\"arn:aws:s3:::test-bucket/*\"\
        ,\"arn:aws:s3:::test-bucket\"]}]}"
      "PublicAccessBlockConfiguration":
        "BlockPublicAcls": false
        "BlockPublicPolicy": false
        "IgnorePublicAcls": false
        "RestrictPublicBuckets": false
      "Versioning":
  - ExpectedResult: false
    Name: Bucket Does Not Have Lifecycle Configuration
    Resource:
      "CreationDate": "2019-01-01T00:00:00Z"
      "EncryptionRules":
        - "ApplyServerSideEncryptionByDefault":
            "KMSMasterKeyID":
            "SSEAlgorithm": "AES256"
      "Grants":
      "LifecycleRules":
      "Location": "us-east-2"
      "LoggingPolicy":
      "MFADelete":
      "Name": "bucket-name"
      "Owner":
        "DisplayName": "user.name"
        "ID": "11112223334445556667778899aaabbbcccdddeeee"
      "Policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\"\
        ,\"Principal\":{\"AWS\":\"arn:aws:iam::123456789012:root\"},\"Action\":[\"\
        s3:ListBucket\",\"s3:PutObject\"],\"Resource\":[\"arn:aws:s3:::test-bucket/*\"\
        ,\"arn:aws:s3:::test-bucket\"]}]}"
      "PublicAccessBlockConfiguration":
        "BlockPublicAcls": false
        "BlockPublicPolicy": false
        "IgnorePublicAcls": false
        "RestrictPublicBuckets": false
      "Versioning":
  - ExpectedResult: false
    Name: Bucket Has Insufficient Lifecycle Configuration
    Resource:
      "CreationDate": "2019-01-01T00:00:00Z"
      "EncryptionRules":
        - "ApplyServerSideEncryptionByDefault":
            "KMSMasterKeyID":
            "SSEAlgorithm": "AES256"
      "Grants":
      "LifecycleRules":
        - "AbortIncompleteMultipartUpload":
          "Expiration":
            "Date":
            "Days": 30
            "ExpiredObjectDeleteMarker":
          "Filter":
            "And":
            "Prefix": ""
            "Tag":
          "ID": "ExpireAfter1Year"
          "NoncurrentVersionExpiration":
            "NoncurrentDays": 30
          "NoncurrentVersionTransitions":
          "Prefix":
          "Status": "Enabled"
          "Transitions":
      "Location": "us-east-2"
      "LoggingPolicy":
      "MFADelete":
      "Name": "bucket-name"
      "Owner":
        "DisplayName": "user.name"
        "ID": "11112223334445556667778899aaabbbcccdddeeee"
      "Policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\"\
        ,\"Principal\":{\"AWS\":\"arn:aws:iam::123456789012:root\"},\"Action\":[\"\
        s3:ListBucket\",\"s3:PutObject\"],\"Resource\":[\"arn:aws:s3:::test-bucket/*\"\
        ,\"arn:aws:s3:::test-bucket\"]}]}"
      "PublicAccessBlockConfiguration":
        "BlockPublicAcls": false
        "BlockPublicPolicy": false
        "IgnorePublicAcls": false
        "RestrictPublicBuckets": false
      "Versioning":
  - ExpectedResult: false
    Name: Lifecycle Configuration Null Test
    Resource:
      "CreationDate": "2019-01-01T00:00:00Z"
      "EncryptionRules":
        - "ApplyServerSideEncryptionByDefault":
            "KMSMasterKeyID":
            "SSEAlgorithm": "AES256"
      "Grants":
      "LifecycleRules":
        - "AbortIncompleteMultipartUpload":
          "Expiration":
            "Date":
            "Days":
            "ExpiredObjectDeleteMarker":
          "Filter":
            "And":
            "Prefix": ""
            "Tag":
          "ID": "ExpireAfter1Year"
          "NoncurrentVersionExpiration":
            "NoncurrentDays":
          "NoncurrentVersionTransitions":
          "Prefix":
          "Status": "Enabled"
          "Transitions":
      "Location": "us-east-2"
      "LoggingPolicy":
      "MFADelete":
      "Name": "bucket-name"
      "Owner":
        "DisplayName": "user.name"
        "ID": "11112223334445556667778899aaabbbcccdddeeee"
      "Policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\"\
        ,\"Principal\":{\"AWS\":\"arn:aws:iam::123456789012:root\"},\"Action\":[\"\
        s3:ListBucket\",\"s3:PutObject\"],\"Resource\":[\"arn:aws:s3:::test-bucket/*\"\
        ,\"arn:aws:s3:::test-bucket\"]}]}"
      "PublicAccessBlockConfiguration":
        "BlockPublicAcls": false
        "BlockPublicPolicy": false
        "IgnorePublicAcls": false
        "RestrictPublicBuckets": false
      "Versioning":
