AnalysisType: policy
Description: >-
  This policy validates that S3 buckets have an Object Lock configuration enabled.
  This should be used with specific suppression lists to ensure it is applied only
  to appropriate S3 buckets, such as those containing CloudTrail or other auditable
  records.
DisplayName: "AWS S3 Bucket Object Lock Configured"
Enabled: false
Filename: aws_s3_bucket_object_lock_configured.py
PolicyID: "AWS.S3.BucketObjectLockConfigured"
Reference: https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock.html
Reports:
  MITRE ATT&CK:
    - TA0040:T1485
  PCI:
    - 10.5.3
ResourceTypes:
  - AWS.S3.Bucket
Runbook: >-
  Create a new S3 bucket with an appropriate Object Lock configuration and point audit
  records to that bucket.
Severity: Low
Tags:
  - AWS
  - S3
  - PCI
  - Impact:Data Destruction
Tests:
  - ExpectedResult: false
    Name: Object Lock Configured With Governance
    Resource:
      "AccountId": "123456789012"
      "Arn": "arn:aws:s3:::example-bucket"
      "EncryptionRules":
        - "ApplyServerSideEncryptionByDefault":
            "KMSMasterKeyID":
            "SSEAlgorithm": "AES256"
      "Grants":
        - "Grantee":
            "DisplayName": "example.user"
            "EmailAddress":
            "ID": "1"
            "Type": "CanonicalUser"
            "URI":
          "Permission": "FULL_CONTROL"
      "LifecycleRules":
      "LoggingPolicy":
      "MFADelete": "Disabled"
      "Name": "example-bucket"
      "ObjectLockConfiguration":
        "ObjectLockEnabled": "Enabled"
        "Rule":
          "DefaultRetention":
            "Days": 1
            "Mode": "GOVERNANCE"
            "Years":
      "Owner":
        "DisplayName": "example.user"
        "ID": "1"
      "Policy":
      "PublicAccessBlockConfiguration":
        "BlockPublicAcls": true
        "BlockPublicPolicy": true
        "IgnorePublicAcls": true
        "RestrictPublicBuckets": true
      "Region": "us-west-2"
      "ResourceId": "arn:aws:s3:::example-bucket"
      "ResourceType": "AWS.S3.Bucket"
      "Tags":
        "environment": "pci"
      "TimeCreated": "2019-01-01T00:00:00.000Z"
      "Versioning": "Enabled"
  - ExpectedResult: true
    Name: Object Lock Configured With Compliance
    Resource:
      "AccountId": "123456789012"
      "Arn": "arn:aws:s3:::example-bucket"
      "EncryptionRules":
        - "ApplyServerSideEncryptionByDefault":
            "KMSMasterKeyID":
            "SSEAlgorithm": "AES256"
      "Grants":
        - "Grantee":
            "DisplayName": "example.user"
            "EmailAddress":
            "ID": "1"
            "Type": "CanonicalUser"
            "URI":
          "Permission": "FULL_CONTROL"
      "LifecycleRules":
      "LoggingPolicy":
      "MFADelete": "Disabled"
      "Name": "example-bucket"
      "ObjectLockConfiguration":
        "ObjectLockEnabled": "Enabled"
        "Rule":
          "DefaultRetention":
            "Days": 365
            "Mode": "COMPLIANCE"
            "Years":
      "Owner":
        "DisplayName": "example.user"
        "ID": "1"
      "Policy":
      "PublicAccessBlockConfiguration":
        "BlockPublicAcls": true
        "BlockPublicPolicy": true
        "IgnorePublicAcls": true
        "RestrictPublicBuckets": true
      "Region": "us-west-2"
      "ResourceId": "arn:aws:s3:::example-bucket"
      "ResourceType": "AWS.S3.Bucket"
      "Tags":
        "environment": "pci"
      "TimeCreated": "2019-01-01T00:00:00.000Z"
      "Versioning": "Enabled"
  - ExpectedResult: false
    Name: Object Lock Not Configured
    Resource:
      "AccountId": "123456789012"
      "Arn": "arn:aws:s3:::example-bucket"
      "EncryptionRules":
        - "ApplyServerSideEncryptionByDefault":
            "KMSMasterKeyID":
            "SSEAlgorithm": "AES256"
      "Grants":
        - "Grantee":
            "DisplayName": "example.user"
            "EmailAddress":
            "ID": "1"
            "Type": "CanonicalUser"
            "URI":
          "Permission": "FULL_CONTROL"
      "LifecycleRules":
      "LoggingPolicy":
      "MFADelete": "Disabled"
      "Name": "example-bucket"
      "ObjectLockConfiguration":
        "ObjectLockEnabled": "Disabled"
        "Rule":
      "Owner":
        "DisplayName": "example.user"
        "ID": "1"
      "Policy":
      "PublicAccessBlockConfiguration":
        "BlockPublicAcls": true
        "BlockPublicPolicy": true
        "IgnorePublicAcls": true
        "RestrictPublicBuckets": true
      "Region": "us-west-2"
      "ResourceId": "arn:aws:s3:::example-bucket"
      "ResourceType": "AWS.S3.Bucket"
      "Tags":
        "environment": "pci"
      "TimeCreated": "2019-01-01T00:00:00.000Z"
      "Versioning": "Enabled"
