AnalysisType: rule
Description: "An external user has been invited to a MongoDB org (no config)."
DisplayName: "MongoDB External User Invited (no config)"
Enabled: true
Filename: mongodb_external_user_invited_no_config.py
Severity: High
Reference: https://www.mongodb.com/docs/v4.2/tutorial/create-users/
Tests:
  - ExpectedResult: false
    Log:
      created: "2023-06-07 16:57:55"
      currentValue: {}
      eventTypeName: INVITED_TO_ORG
      id: 6480b7139bd8a012345ABCDE
      isGlobalAdmin: false
      links:
        - href: https://cloud.mongodb.com/api/atlas/v1.0/orgs/12345xyzlmnce4f17d6e8e130/events/6480b7139bd8a012345ABCDE
          rel: self
      orgId: 12345xyzlmnce4f17d6e8e130
      p_event_time: "2023-06-07 16:57:55"
      p_log_type: MongoDB.OrganizationEvent
      p_parse_time: "2023-06-07 17:04:42.59"
      p_row_id: ea276b16216684d9e198c0d0188a3d
      p_schema_version: 0
      p_source_id: 7c3cb124-9c30-492c-99e6-46518c232d73
      p_source_label: MongoDB
      remoteAddress: 1.2.3.4
      targetUsername: insider@company.com
      userId: 647f654f93bebc69123abc1
      username: user@company.com
    Name: Internal Invite
  - ExpectedResult: true
    Log:
      created: "2023-06-07 16:57:55"
      currentValue: {}
      eventTypeName: INVITED_TO_ORG
      id: 6480b7139bd8a012345ABCDE
      isGlobalAdmin: false
      links:
        - href: https://cloud.mongodb.com/api/atlas/v1.0/orgs/12345xyzlmnce4f17d6e8e130/events/6480b7139bd8a012345ABCDE
          rel: self
      orgId: 12345xyzlmnce4f17d6e8e130
      p_event_time: "2023-06-07 16:57:55"
      p_log_type: MongoDB.OrganizationEvent
      p_parse_time: "2023-06-07 17:04:42.59"
      p_row_id: ea276b16216684d9e198c0d0188a3d
      p_schema_version: 0
      p_source_id: 7c3cb124-9c30-492c-99e6-46518c232d73
      p_source_label: MongoDB
      remoteAddress: 1.2.3.4
      targetUsername: outsider@other.com
      userId: 647f654f93bebc69123abc1
      username: user@company.com
    Name: External User Invite
DedupPeriodMinutes: 60
LogTypes:
  - MongoDB.OrganizationEvent
RuleID: "MongoDB.External.UserInvited.NoConfig"
Threshold: 1
