AnalysisType: policy
Description: >-
  This policy validates that all application load balancers have an associated Web
  ACl to enforce protections against various web attacks.
DisplayName: "AWS Application Load Balancer Web ACL"
Enabled: false
Filename: aws_application_load_balancer_web_acl.py
PolicyID: "AWS.ApplicationLoadBalancer.WebACL"
Reference: 
  https://aws.amazon.com/blogs/aws/aws-web-application-firewall-waf-for-application-load-balancers/
Reports:
  MITRE ATT&CK:
    - TA0001:T1190
ResourceTypes:
  - AWS.ELBV2.ApplicationLoadBalancer
Runbook: >-
  https://docs.runpanther.io/alert-runbooks/built-in-policies/aws-application-load-balancer-has-web-acl
Severity: High
Tags:
  - AWS
  - Configuration Required
  - Security Control
  - Initial Access:Exploit Public-Facing Application
Tests:
  - ExpectedResult: false
    Name: Load Balancer Does Not Have Required WAF Web ACL
    Resource:
      "AvailabilityZones":
        - "LoadBalancerAddresses":
          "SubnetId": "subnet-111222333"
          "ZoneName": "us-west-2d"
        - "LoadBalancerAddresses":
          "SubnetId": "subnet-111222333"
          "ZoneName": "us-west-2a"
      "CanonicalHostedZoneId": "111222333AAA"
      "CreatedTime": "2019-01-01T00:00:00.00Z"
      "DNSName": "example-lb-111222333.us-west-2.elb.amazonaws.com"
      "IpAddressType": "ipv4"
      "LoadBalancerArn": "TEST_LOAD_BALANCER_ARN"
      "LoadBalancerName": "TEST_LOAD_BALANCER"
      "Scheme": "internal"
      "SecurityGroups":
        - "sg-111222333444"
      "State":
        "Code": "active"
        "Reason":
      "Type": "application"
      "VpcId": "vpc-111222333"
      "WebAcl":
  - ExpectedResult: true
    Name: Load Balancer Does Not Require WAF Web ACL
    Resource:
      "AvailabilityZones":
        - "LoadBalancerAddresses":
          "SubnetId": "subnet-111222333"
          "ZoneName": "us-west-2d"
        - "LoadBalancerAddresses":
          "SubnetId": "subnet-111222333"
          "ZoneName": "us-west-2a"
      "CanonicalHostedZoneId": "111222333AAA"
      "CreatedTime": "2019-01-01T00:00:00.00Z"
      "DNSName": "example-lb-111222333.us-west-2.elb.amazonaws.com"
      "IpAddressType": "ipv4"
      "LoadBalancerArn": "TEST_LOAD_BALANCER_ARN_NO_WEB_ACL"
      "LoadBalancerName": "TEST_LOAD_BALANCER"
      "Scheme": "internal"
      "SecurityGroups":
        - "sg-111222333444"
      "State":
        "Code": "active"
        "Reason":
      "Type": "application"
      "VpcId": "vpc-111222333"
      "WebAcl":
  - ExpectedResult: true
    Name: Load Balancer Has Correct WAF Web ACL
    Resource:
      "AvailabilityZones":
        - "LoadBalancerAddresses":
          "SubnetId": "subnet-111222333"
          "ZoneName": "us-west-2d"
        - "LoadBalancerAddresses":
          "SubnetId": "subnet-111222333"
          "ZoneName": "us-west-2a"
      "CanonicalHostedZoneId": "111222333AAA"
      "CreatedTime": "2019-01-01T00:00:00.00Z"
      "DNSName": "example-lb-111222333.us-west-2.elb.amazonaws.com"
      "IpAddressType": "ipv4"
      "LoadBalancerArn": "TEST_LOAD_BALANCER_ARN"
      "LoadBalancerName": "TEST_LOAD_BALANCER"
      "Scheme": "internal"
      "SecurityGroups":
        - "sg-111222333444"
      "State":
        "Code": "active"
        "Reason":
      "Type": "application"
      "VpcId": "vpc-111222333"
      "WebAcl":
        "DefaultAction":
          "Type": "ALLOW"
        "MetricName": "examplewebacl"
        "Name": "example-web-acl"
        "Rules":
          - "Action":
              "Type": "BLOCK"
            "ExcludedRules":
            "OverrideAction":
            "Priority": 2
            "RuleId": "111222-1111-1111-1111-111222333444"
            "Type": "REGULAR"
          - "Action":
              "Type": "COUNT"
            "ExcludedRules":
            "OverrideAction":
            "Priority": 1
            "RuleId": "111222-1111-2222-3333-111222333444"
            "Type": "REGULAR"
        "WebACLArn": "arn:aws:waf-regional:us-west-2:123456789012:webacl/111222-1111-2222-3333-111222333444"
        "WebACLId": "TEST_WAF_WEB_ACL_ID"
