AnalysisType: pack
Description: Group of all Push Security detections
DisplayName: Panther Push Security Pack
PackDefinition:
  IDs:
    - Push.Security.App.Banner.Acknowledged
    - Push.Security.MFA.Method.Changed
    - Push.Security.New.App.Detected
    - Push.Security.New.SaaS.Account.Created
    - Push.Security.Open.Security.Finding
    - Push.Security.Phishable.MFA.Method
    - Push.Security.Phishing.Attack
PackID: PantherManaged.PushSecurity
