# azure-pipelines.yml
parameters:
  - name: vmImage
    displayName: 'VM Image'
    type: string
    default: 'ubuntu-latest'
  - name: poolName
    displayName: 'Pool Name (optional)'
    type: string
    default: local-tate
  - name: targetBranch
    displayName: 'Target Branch for Upload'
    type: string
    default: 'develop'
  - name: pythonVersion
    displayName: 'Python Version'
    type: string
    default: '3.x'
trigger:
  branches:
    include:
      - develop # Explicitly trigger on pushes/merges to develop
      - main # Include other main branches if you have them
pr:
  branches:
    include:
      - develop # Trigger on PRs targeting develop
      - features/* # Trigger on PRs from feature branches
pool:
  name: local-tate
stages:
  - template: stages/validate.yml
    parameters:
      vmImage: ${{ parameters.vmImage }}
      poolName: ${{ parameters.poolName }}
      pythonVersion: ${{ parameters.pythonVersion }}
  - template: stages/validate-and-test.yml
    parameters:
      vmImage: ${{ parameters.vmImage }}
      poolName: ${{ parameters.poolName }}
      pythonVersion: ${{ parameters.pythonVersion }}
  - template: stages/upload.yml
    parameters:
      vmImage: ${{ parameters.vmImage }}
      poolName: ${{ parameters.poolName }}
      pythonVersion: ${{ parameters.pythonVersion }}
