# azure-pipelines.yml
parameters:
  - name: vmImage
    displayName: 'VM Image'
    type: string
    default: 'ubuntu-latest'
  - name: poolName
    displayName: 'Pool Name (optional)'
    type: string
    default: ''
  - name: targetBranch
    displayName: 'Target Branch for Upload'
    type: string
    default: 'develop'
  - name: pythonVersion
    displayName: 'Python Version'
    type: string
    default: '3.x'
# Triggers are fixed - define all branches that should trigger PR or push builds
trigger:
  branches:
    include:
      - ${{ parameters.targetBranch }} # e.g., 'develop'
      - main # Or any other main development branches you might push to
pr:
  branches:
    include:
      - ${{ parameters.targetBranch }} # e.g., 'develop' for PRs targeting it
      - features/* # Optional: include feature branches for PRs
# Define pool at the top level, without conditional logic here.
# If poolName is empty, it will default to vmImage.
# If you *must* have conditional pool logic, it needs to be inside jobs/stages.
pool:
  ${{ if ne(parameters.poolName, '') }}: # This specific 'if' condition is acceptable here for pool name vs vmImage
    name: ${{ parameters.poolName }}
  vmImage: ${{ parameters.vmImage }}
  # If poolName is provided, vmImage will be ignored for that pool.
  # If poolName is empty, it will use the vmImage.
stages:
  - template: stages/validate-and-test.yml
    parameters:
      vmImage: ${{ parameters.vmImage }}
      poolName: ${{ parameters.poolName }}
      pythonVersion: ${{ parameters.pythonVersion }}
  - template: stages/upload.yml
    parameters:
      targetBranch: ${{ parameters.targetBranch }} # Pass targetBranch to the upload template
      vmImage: ${{ parameters.vmImage }}
      poolName: ${{ parameters.poolName }}
      pythonVersion: ${{ parameters.pythonVersion }}
