# azure-pipelines.yml
parameters:
  - name: vmImage
    displayName: 'VM Image'
    type: string
    default: 'ubuntu-latest'
  - name: poolName
    displayName: 'Pool Name (optional)'
    type: string
    default: 'local-tate'
  - name: targetBranch
    displayName: 'Target Branch for Upload'
    type: string
    default: 'develop'
trigger:
  branches:
    include:
      - ${{ parameters.targetBranch }} # Trigger on pushes/merges to the target branch
pr:
  branches:
    include:
      - ${{ parameters.targetBranch }} # Trigger on PRs targeting the target branch
      - features/* # Optional: include feature branches for PRs
# Define pool at the top level to be used by all jobs by default,
# or you can define it within each stage/job.
pool:
  ${{ if ne(parameters.poolName, '') }}:
    name: ${{ parameters.poolName }}
  vmImage: ${{ parameters.vmImage }}
stages:
  - template: stages/validate-and-test.yml # Will run for both PRs and direct pushes/merges
    parameters:
      vmImage: ${{ parameters.vmImage }}
      poolName: ${{ parameters.poolName }}
  - template: stages/upload.yml # Will only run for direct pushes/merges to the target branch
    parameters:
      targetBranch: ${{ parameters.targetBranch }}
      vmImage: ${{ parameters.vmImage }}
      poolName: ${{ parameters.poolName }}
