AnalysisType: rule
DedupPeriodMinutes: 60
Description: >-
  This rule detects when password settings are insecure.
DisplayName: "ZIA Insecure Password Settings"
Enabled: true
Filename: zia_insecure_password_settings.py
LogTypes:
  - Zscaler.ZIA.AdminAuditLog
Reference: https://help.zscaler.com/zia/customizing-your-admin-account-settings
Reports:
  MITRE ATT&CK:
    - TA0005:T1556.009
RuleID: "ZIA.Insecure.Password.Settings"
Runbook: >-
  Set the secure password configurations.
Severity: Medium
Tests:
  - ExpectedResult: true
    Log:
      "event":
        "action": "UPDATE"
        "adminid": "admin@test.zscalerbeta.net"
        "auditlogtype": "ZIA"
        "category": "AUTHENTICATION_SETTINGS"
        "clientip": "1.2.3.4"
        "errorcode": "None"
        "interface": "UI"
        "postaction":
          "authFrequency": "PERMANENT_COOKIE"
          "autoProvision": false
          "directorySyncMigrateToScimEnabled": false
          "kerberosEnabled": false
          "mobileAdminSamlIdpEnabled": false
          "oneTimeAuth": "OTP_DISABLED"
          "orgAuthType": "SAFECHANNEL_DIR"
          "passwordExpiry": "NEVER"
          "passwordStrength": "NONE"
          "samlEnabled": false
        "preaction":
          "authFrequency": "DAILY_COOKIE"
          "autoProvision": false
          "directorySyncMigrateToScimEnabled": false
          "kerberosEnabled": false
          "mobileAdminSamlIdpEnabled": false
          "oneTimeAuth": "OTP_DISABLED"
          "orgAuthType": "SAFECHANNEL_DIR"
          "passwordExpiry": "NEVER"
          "passwordStrength": "NONE"
          "samlEnabled": false
        "recordid": "356"
        "resource": "None"
        "result": "SUCCESS"
        "subcategory": "AUTH_SETTINGS_PROFILE"
        "time": "2024-11-04 16:29:24.000000000"
      "sourcetype": "zscalernss-audit"
    Name: Permanent cookie
  - ExpectedResult: true
    Log:
      "event":
        "action": "UPDATE"
        "adminid": "admin@test.zscalerbeta.net"
        "auditlogtype": "ZIA"
        "category": "AUTHENTICATION_SETTINGS"
        "clientip": "1.2.3.4"
        "errorcode": "None"
        "interface": "UI"
        "postaction":
          "authFrequency": "DAILY_COOKIE"
          "autoProvision": false
          "directorySyncMigrateToScimEnabled": false
          "kerberosEnabled": false
          "mobileAdminSamlIdpEnabled": false
          "oneTimeAuth": "OTP_LINK"
          "orgAuthType": "SAFECHANNEL_DIR"
          "passwordExpiry": "NEVER"
          "passwordStrength": "NONE"
          "samlEnabled": false
        "preaction":
          "authFrequency": "DAILY_COOKIE"
          "autoProvision": false
          "directorySyncMigrateToScimEnabled": false
          "kerberosEnabled": false
          "mobileAdminSamlIdpEnabled": false
          "oneTimeAuth": "OTP_DISABLED"
          "orgAuthType": "SAFECHANNEL_DIR"
          "passwordExpiry": "NEVER"
          "passwordStrength": "NONE"
          "samlEnabled": false
        "recordid": "357"
        "resource": "None"
        "result": "SUCCESS"
        "subcategory": "AUTH_SETTINGS_PROFILE"
        "time": "2024-11-04 16:29:40.000000000"
      "sourcetype": "zscalernss-audit"
    Name: Password expiry - never
  - ExpectedResult: true
    Log:
      "event":
        "action": "UPDATE"
        "adminid": "admin@test.zscalerbeta.net"
        "auditlogtype": "ZIA"
        "category": "AUTHENTICATION_SETTINGS"
        "clientip": "1.2.3.4"
        "errorcode": "None"
        "interface": "UI"
        "postaction":
          "authFrequency": "DAILY_COOKIE"
          "autoProvision": false
          "directorySyncMigrateToScimEnabled": false
          "kerberosEnabled": false
          "mobileAdminSamlIdpEnabled": false
          "oneTimeAuth": "OTP_DISABLED"
          "orgAuthType": "SAFECHANNEL_DIR"
          "passwordExpiry": "SIX_MONTHS"
          "passwordStrength": "NONE"
          "samlEnabled": false
        "preaction":
          "authFrequency": "DAILY_COOKIE"
          "autoProvision": false
          "directorySyncMigrateToScimEnabled": false
          "kerberosEnabled": false
          "mobileAdminSamlIdpEnabled": false
          "oneTimeAuth": "OTP_DISABLED"
          "orgAuthType": "SAFECHANNEL_DIR"
          "passwordExpiry": "NEVER"
          "passwordStrength": "NONE"
          "samlEnabled": false
        "recordid": "361"
        "resource": "None"
        "result": "SUCCESS"
        "subcategory": "AUTH_SETTINGS_PROFILE"
        "time": "2024-11-04 16:30:36.000000000"
      "sourcetype": "zscalernss-audit"
    Name: Password strength - none
  - ExpectedResult: false
    Log:
      "event":
        "action": "SIGN_IN"
        "adminid": "admin@test.zscalerbeta.net"
        "auditlogtype": "ZIA"
        "category": "LOGIN"
        "clientip": "1.2.3.4"
        "errorcode": "None"
        "interface": "UI"
        "postaction": {}
        "preaction": {}
        "recordid": "354"
        "resource": "None"
        "result": "SUCCESS"
        "subcategory": "LOGIN"
        "time": "2024-11-04 16:27:37.000000000"
      "sourcetype": "zscalernss-audit"
    Name: Other event
Threshold: 1
