AnalysisType: rule
Description: 'Detects AWS Config Service disabling


  Status: test


  Author: vitaliy0x1

  False Positives: Valid change in AWS Config Service'
DisplayName: AWS Config Disabling Channel/Recorder
Enabled: true
Filename: aws_config_disable_recording.py
LogTypes:
- AWS.CloudTrail
Reference: https://docs.aws.amazon.com/config/latest/developerguide/cloudtrail-log-files-for-aws-config.html
Reports:
  MITRE ATT&CK:
  - T1562.001
RuleID: aws_config_disable_recording
Severity: High
Tags:
- Sigma
- defense-evasion
- t1562.001
