AnalysisType: rule
Description: 'Detects when a user disables a critical security feature for an organization.


  Status: test


  Author: Muhammad Faisal (@faisalusuf)

  False Positives: Approved administrator/owner activities.'
DisplayName: Github High Risk Configuration Disabled
Enabled: true
Filename: github_disable_high_risk_configuration.py
LogTypes:
- GitHub.Audit
Reference: https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/disabling-oauth-app-access-restrictions-for-your-organization
Reports:
  MITRE ATT&CK:
  - TA0006:T1556
  - TA0005:T1556
  - TA0003:T1556
RuleID: github_disable_high_risk_configuration
Severity: High
Tags:
- Sigma
- credential-access
- defense-evasion
- persistence
- t1556
