AnalysisType: rule
Description: 'Detects when an application Sign-on Policy is modified or deleted.


  Status: test


  Author: Austin Songer @austinsonger

  False Positives: Unknown'
DisplayName: Okta Application Sign-On Policy Modified or Deleted
Enabled: true
Filename: okta_application_sign_on_policy_modified_or_deleted.py
LogTypes:
- Okta.SystemLog
Reference: https://developer.okta.com/docs/reference/api/system-log/
Reports:
  MITRE ATT&CK: []
RuleID: okta_application_sign_on_policy_modified_or_deleted
Severity: Medium
Tags:
- Sigma
- impact
