AnalysisType: rule
Description: >-
  The application level firewall blocks unwanted network connections made to your
  computer from other computers on your network.
DisplayName: "MacOS ALF is misconfigured"
Enabled: true
Filename: osquery_mac_application_firewall.py
LogTypes:
  - Osquery.Differential
Reference: https://support.apple.com/en-us/HT201642
Reports:
  CIS:
    - 2.6.3
    - 2.6.4
  MITRE ATT&CK:
    - TA0005:T1562
RuleID: "Osquery.Mac.ApplicationFirewallSettings"
Runbook: >-
  Re-enable the firewall manually or with configuration management
Severity: High
SummaryAttributes:
  - name
  - hostIdentifier
  - action
Tags:
  - Osquery
  - MacOS
  - Security Control
  - Defense Evasion:Impair Defenses
Tests:
  - ExpectedResult: true
    Log:
      "action": "added"
      "columns":
        "allow_signed_enabled": "0"
        "firewall_unload": "0"
        "global_state": "0"
        "logging_enabled": "0"
        "logging_option": "0"
        "stealth_enabled": "0"
        "version": "1.6"
      "hostIdentifier": "test-host"
      "name": "pack_incident-response_alf"
    Name: ALF Disabled
  - ExpectedResult: false
    Log:
      "action": "added"
      "columns":
        "allow_signed_enabled": "1"
        "firewall_unload": "0"
        "global_state": "1"
        "logging_enabled": "1"
        "logging_option": "0"
        "stealth_enabled": "1"
        "version": "1.6"
      "hostIdentifier": "test-host"
      "name": "pack_incident-response_alf"
    Name: ALF Enabled
