AnalysisType: rule
Description: >-
  An AWS Config Recorder or Delivery Channel was disabled or deleted
DisplayName: "AWS Config Service Disabled"
Enabled: true
Filename: aws_config_service_disabled_deleted.py
LogTypes:
  - AWS.CloudTrail
Reference: https://aws.amazon.com/config/
Reports:
  CIS:
    - 3.9
  MITRE ATT&CK:
    - TA0005:T1562
RuleID: "AWS.ConfigService.DisabledDeleted"
Runbook: >-
  Verify that the Config Service changes were authorized. If not, revert them and
  investigate who caused the change. Consider altering permissions to prevent this
  from happening again in the future.
Severity: Medium
SummaryAttributes:
  - eventName
  - userAgent
  - sourceIpAddress
  - recipientAccountId
  - p_any_aws_arns
Tags:
  - AWS
  - Security Control
  - Defense Evasion:Impair Defenses
Tests:
  - ExpectedResult: false
    Log:
      "awsRegion": "us-west-2"
      "eventID": "1"
      "eventName": "PutDeliveryChannel"
      "eventSource": "config.amazonaws.com"
      "eventTime": "2019-01-01T00:00:00Z"
      "eventType": "AwsApiCall"
      "eventVersion": "1.05"
      "recipientAccountId": "123456789012"
      "requestID": "1"
      "requestParameters":
        "configurationRecorderName": "default"
      "responseElements":
      "sourceIPAddress": "111.111.111.111"
      "userAgent": "console.amazonaws.com"
      "userIdentity":
        "accessKeyId": "1"
        "accountId": "123456789012"
        "arn": "arn:aws:sts::123456789012:assumed-role/tester"
        "principalId": "1111:tester"
        "sessionContext":
          "attributes":
            "creationDate": "2019-01-01T00:00:00Z"
            "mfaAuthenticated": "true"
          "sessionIssuer":
            "accountId": "123456789012"
            "arn": "arn:aws:iam::123456789012:role/tester"
            "principalId": "1111"
            "type": "Role"
            "userName": "tester"
          "webIdFederationData": {}
        "type": "AssumedRole"
    Name: Config Recorder Delivery Channel Created
  - ExpectedResult: true
    Log:
      "awsRegion": "us-west-2"
      "eventID": "1"
      "eventName": "DeleteDeliveryChannel"
      "eventSource": "config.amazonaws.com"
      "eventTime": "2019-01-01T00:00:00Z"
      "eventType": "AwsApiCall"
      "eventVersion": "1.05"
      "recipientAccountId": "123456789012"
      "requestID": "1"
      "requestParameters":
        "configurationRecorderName": "default"
      "responseElements":
      "sourceIPAddress": "111.111.111.111"
      "userAgent": "console.amazonaws.com"
      "userIdentity":
        "accessKeyId": "1"
        "accountId": "123456789012"
        "arn": "arn:aws:sts::123456789012:assumed-role/tester"
        "principalId": "1111:tester"
        "sessionContext":
          "attributes":
            "creationDate": "2019-01-01T00:00:00Z"
            "mfaAuthenticated": "true"
          "sessionIssuer":
            "accountId": "123456789012"
            "arn": "arn:aws:iam::123456789012:role/tester"
            "principalId": "1111"
            "type": "Role"
            "userName": "tester"
          "webIdFederationData": {}
        "type": "AssumedRole"
    Name: Config Recorder Deleted
  - ExpectedResult: false
    Log:
      "awsRegion": "us-west-2"
      "errorCode": "NoSuchDeliveryChannelException"
      "eventID": "1"
      "eventName": "DeleteDeliveryChannel"
      "eventSource": "config.amazonaws.com"
      "eventTime": "2019-01-01T00:00:00Z"
      "eventType": "AwsApiCall"
      "eventVersion": "1.05"
      "recipientAccountId": "123456789012"
      "requestID": "1"
      "requestParameters":
        "configurationRecorderName": "default"
      "responseElements":
      "sourceIPAddress": "111.111.111.111"
      "userAgent": "console.amazonaws.com"
      "userIdentity":
        "accessKeyId": "1"
        "accountId": "123456789012"
        "arn": "arn:aws:sts::123456789012:assumed-role/tester"
        "principalId": "1111:tester"
        "sessionContext":
          "attributes":
            "creationDate": "2019-01-01T00:00:00Z"
            "mfaAuthenticated": "true"
          "sessionIssuer":
            "accountId": "123456789012"
            "arn": "arn:aws:iam::123456789012:role/tester"
            "principalId": "1111"
            "type": "Role"
            "userName": "tester"
          "webIdFederationData": {}
        "type": "AssumedRole"
    Name: Error Deleting Config Recorder
