AnalysisType: rule
Description: >-
  An account wide security configuration was changed.
DisplayName: "Account Security Configuration Changed"
Enabled: true
Filename: aws_security_configuration_change.py
LogTypes:
  - AWS.CloudTrail
Reference: 
  https://docs.aws.amazon.com/prescriptive-guidance/latest/aws-startup-security-baseline/controls-acct.html
Reports:
  MITRE ATT&CK:
    - TA0005:T1562
RuleID: "AWS.CloudTrail.SecurityConfigurationChange"
Runbook: >-
  Verify that this change was planned. If not, revert the change and update the access
  control policies to ensure this doesn't happen again.
Severity: Medium
SummaryAttributes:
  - eventName
  - userAgent
  - sourceIpAddress
  - recipientAccountId
  - p_any_aws_arns
Tags:
  - AWS
  - Defense Evasion:Impair Defenses
Tests:
  - ExpectedResult: true
    Log:
      "awsRegion": "us-west-2"
      "eventID": "1111"
      "eventName": "DeleteTrail"
      "eventSource": "cloudtrail.amazonaws.com"
      "eventTime": "2019-01-01T00:00:00Z"
      "eventType": "AwsApiCall"
      "eventVersion": "1.05"
      "readOnly": false
      "recipientAccountId": "123456789012"
      "requestID": "1111"
      "requestParameters":
        "name": "example-trail"
      "responseElements":
      "sourceIPAddress": "111.111.111.111"
      "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)"
      "userIdentity":
        "accessKeyId": "1111"
        "accountId": "123456789012"
        "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user"
        "invokedBy": "cloudformation.amazonaws.com"
        "principalId": "1111"
        "sessionContext":
          "attributes":
            "creationDate": "2019-01-01T00:00:00Z"
            "mfaAuthenticated": "true"
          "sessionIssuer":
            "accountId": "123456789012"
            "arn": "arn:aws:iam::123456789012:role/example-role"
            "principalId": "1111"
            "type": "Role"
            "userName": "example-role"
          "webIdFederationData": {}
        "type": "AssumedRole"
    Name: Security Configuration Changed
  - ExpectedResult: false
    Log:
      "awsRegion": "us-west-2"
      "eventID": "1111"
      "eventName": "DescribeTrail"
      "eventSource": "cloudtrail.amazonaws.com"
      "eventTime": "2019-01-01T00:00:00Z"
      "eventType": "AwsApiCall"
      "eventVersion": "1.05"
      "readOnly": false
      "recipientAccountId": "123456789012"
      "requestID": "1111"
      "requestParameters":
        "name": "example-trail"
      "responseElements":
      "sourceIPAddress": "111.111.111.111"
      "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)"
      "userIdentity":
        "accessKeyId": "1111"
        "accountId": "123456789012"
        "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user"
        "invokedBy": "cloudformation.amazonaws.com"
        "principalId": "1111"
        "sessionContext":
          "attributes":
            "creationDate": "2019-01-01T00:00:00Z"
            "mfaAuthenticated": "true"
          "sessionIssuer":
            "accountId": "123456789012"
            "arn": "arn:aws:iam::123456789012:role/example-role"
            "principalId": "1111"
            "type": "Role"
            "userName": "example-role"
          "webIdFederationData": {}
        "type": "AssumedRole"
    Name: Security Configuration Not Changed
  - ExpectedResult: false
    Log:
      "awsRegion": "us-west-2"
      "eventID": "1111"
      "eventName": "PutPolicy"
      "eventSource": "iam.amazonaws.com"
      "eventTime": "2019-01-01T00:00:00Z"
      "eventType": "AwsApiCall"
      "eventVersion": "1.05"
      "readOnly": false
      "recipientAccountId": "123456789012"
      "requestID": "1111"
      "requestParameters":
        "name": "example-trail"
      "responseElements":
      "sourceIPAddress": "111.111.111.111"
      "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)"
      "userIdentity":
        "accessKeyId": "1111"
        "accountId": "123456789012"
        "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user"
        "invokedBy": "cloudformation.amazonaws.com"
        "principalId": "1111"
        "sessionContext":
          "attributes":
            "creationDate": "2019-01-01T00:00:00Z"
            "mfaAuthenticated": "true"
          "sessionIssuer":
            "accountId": "123456789012"
            "arn": "arn:aws:iam::123456789012:role/example-role"
            "principalId": "1111"
            "type": "Role"
            "userName": "example-role"
          "webIdFederationData": {}
        "type": "AssumedRole"
    Name: Non Security Configuration Change
  - ExpectedResult: false
    Log:
      "awsRegion": "us-west-2"
      "errorCode": "ConflictException"
      "eventID": "1111"
      "eventName": "DeleteTrail"
      "eventSource": "cloudtrail.amazonaws.com"
      "eventTime": "2019-01-01T00:00:00Z"
      "eventType": "AwsApiCall"
      "eventVersion": "1.05"
      "readOnly": false
      "recipientAccountId": "123456789012"
      "requestID": "1111"
      "requestParameters":
        "name": "example-trail"
      "responseElements":
      "sourceIPAddress": "111.111.111.111"
      "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)"
      "userIdentity":
        "accessKeyId": "1111"
        "accountId": "123456789012"
        "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user"
        "invokedBy": "cloudformation.amazonaws.com"
        "principalId": "1111"
        "sessionContext":
          "attributes":
            "creationDate": "2019-01-01T00:00:00Z"
            "mfaAuthenticated": "true"
          "sessionIssuer":
            "accountId": "123456789012"
            "arn": "arn:aws:iam::123456789012:role/example-role"
            "principalId": "1111"
            "type": "Role"
            "userName": "example-role"
          "webIdFederationData": {}
        "type": "AssumedRole"
    Name: Security Configuration Not Changed - Error
  - ExpectedResult: false
    Log:
      "awsRegion": "us-west-2"
      "eventID": "1111"
      "eventName": "DeleteRule"
      "eventSource": "cloudtrail.amazonaws.com"
      "eventTime": "2019-01-01T00:00:00Z"
      "eventType": "AwsApiCall"
      "eventVersion": "1.05"
      "readOnly": false
      "recipientAccountId": "123456789012"
      "requestID": "1111"
      "requestParameters":
        "name": "example-trail"
      "responseElements":
      "sourceIPAddress": "111.111.111.111"
      "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)"
      "userIdentity":
        "accessKeyId": "1111"
        "accountId": "123456789012"
        "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user"
        "invokedBy": "cloudformation.amazonaws.com"
        "principalId": "1111"
        "sessionContext":
          "attributes":
            "creationDate": "2019-01-01T00:00:00Z"
            "mfaAuthenticated": "true"
          "sessionIssuer":
            "accountId": "123456789012"
            "arn": "arn:aws:iam::123456789012:role/example-role"
            "principalId": "1111"
            "type": "Role"
            "userName": "ExampleUser"
          "webIdFederationData": {}
        "type": "AssumedRole"
    Mocks:
      - objectName: ALLOW_LIST
        returnValue: '[{"userName": "ExampleUser", "eventName": "DeleteRule"}]'
    Name: Security Configuration Changed - Allowlisted User
