AnalysisType: rule
RuleID: Wiz.Update.Scanner.Settings
Description: This rule detects updates of Wiz scanner settings.
DisplayName: Wiz Update Scanner Settings
Runbook: Verify that this change was planned. If not, revert the change and ensure this doesn't happen again.
Reference: https://www.wiz.io/academy/secret-scanning
Enabled: false
Filename: wiz_update_scanner_settings.py
Severity: Medium
Reports:
  MITRE ATT&CK:
    - TA0005:T1562.001  # Impair Defenses: Disable or Modify Tools
LogTypes:
  - Wiz.Audit
DedupPeriodMinutes: 60
Threshold: 1
Tests:
  - Name: UpdateScannerSettings
    ExpectedResult: true
    Log:
      {
        "id": "dd48b7fe-576d-453d-a0d0-1f61425b1bb7",
        "action": "UpdateScannerSettings",
        "requestId": "d5c55350-0d54-46eb-88ee-4942f80e700c",
        "status": "SUCCESS",
        "timestamp": "2024-06-18T12:09:33.985762Z",
        "actionParameters": {
          "input": {
            "patch": {
              "computeResourceGroupMemberScanSamplingEnabled": true,
              "maxComputeResourceGroupMemberScanCount": 2,
              "prioritizeActiveComputeResourceGroupMembers": true
            }
          },
          "selection": [
            "__typename",
            {
              "scannerSettings": [
                "__typename",
                "computeResourceGroupMemberScanSamplingEnabled",
                "maxComputeResourceGroupMemberScanCount",
                {
                  "customFileDetectionList": [
                    "__typename",
                    "id",
                    "url",
                    "fileDetectionCount"
                  ]
                }
              ]
            }
          ]
        },
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "sourceIP": "12.34.56.78",
        "serviceAccount": null,
        "user": {
          "id": "test.user@company.com",
          "name": "user@company.com"
        }
      }
  - Name: CreateUser
    ExpectedResult: false
    Log:
      {
        "id": "220d23be-f07c-4d97-b4a6-87ad04eddb14",
        "action": "CreateUser",
        "requestId": "0d9521b2-c3f8-4a73-bf7c-20257788752e",
        "status": "SUCCESS",
        "timestamp": "2024-07-29T09:40:15.66643Z",
        "actionParameters": {
          "input": {
            "assignedProjectIds": null,
            "email": "testy@company.com",
            "expiresAt": null,
            "name": "Test User",
            "role": "GLOBAL_ADMIN"
          },
          "selection": [
            "__typename",
            {
              "user": [
                "__typename",
                "id"
              ]
            }
          ]
        },
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "sourceIP": "8.8.8.8",
        "serviceAccount": null,
        "user": {
          "id": "someuser@company.com",
          "name": "someuser@company.com"
        }
      }
  - Name: UpdateScannerSettings - Fail
    ExpectedResult: false
    Log:
      {
        "id": "dd48b7fe-576d-453d-a0d0-1f61425b1bb7",
        "action": "UpdateScannerSettings",
        "requestId": "d5c55350-0d54-46eb-88ee-4942f80e700c",
        "status": "FAILED",
        "timestamp": "2024-06-18T12:09:33.985762Z",
        "actionParameters": { },
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "sourceIP": "12.34.56.78",
        "serviceAccount": null,
        "user": {
          "id": "test.user@company.com",
          "name": "user@company.com"
        }
      }
