# Sync workflow for panther-analysis to airflow
name: Airflow Update (Internal)

on:
 workflow_dispatch:
   inputs:
     branch:
       description: "Branch to update Airflow from"
       required: true
       default: "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-airflow:
    runs-on: ubuntu-latest
    if: github.repository == 'panther-labs/panther-analysis'
    steps:
      - name: Checkout panther-analysis
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          path: source

      - name: Checkout Airflow repository
        uses: actions/checkout@v4
        with:
          repository: panther-labs/airflow
          token: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
          path: destination

      - name: Set up Git user
        run: |
          git config --global user.email "github-service-account-automation@panther.io"
          git config --global user.name "panther-bot-automation"

      - name: Debug Git directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Source directory contents:"
          ls -la source
          echo "Destination directory contents:"
          ls -la destination

      - name: Change to destination directory
        run: cd destination

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: destination

      - name: Copy files to Airflow
        run: |
          # Create include directory if it doesn't exist
          mkdir -p destination/include
          # Copy only the specified folders from source to destination
          cp -r source/rules source/correlation_rules source/data_models source/lookup_tables source/policies source/packs destination/include/
          cd destination
          git add include/
          git commit -m "Update Airflow with latest Panther Analysis changes" --gpg-sign
          git push origin HEAD:update-airflow-${GITHUB_RUN_ID}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
          commit-message: "Update Airflow with latest Panther Analysis changes"
          title: "Update Airflow with latest Panther Analysis changes"
          body: "Automated update from Panther Analysis repository"
          branch: "update-airflow-${GITHUB_RUN_ID}"
          base: "main"
          path: "destination"
