name: Build Docker Image (Deprecated)

on:
  pull_request:
    paths:
      - "Dockerfile"

permissions:
  contents: read

jobs:
  test:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout panther-analysis
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a #v4.3.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e #v4.3.0
      - name: Build Image
        run: docker buildx build --load -f Dockerfile -t panther-analysis:latest .
      - name: Test Image
        run: |
          docker run --rm -t panther-analysis:latest pipenv run panther_analysis_tool --version
