name: Sigma Rule Convert

on:
  pull_request:
    branches:
      - lindy/sigma-workflows

permissions:
  contents: read

jobs:
  sigma-rule-convert:
    name: Convert sigma rules to panther rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sigma HQ Codebase rules
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Fetch Release
        run: |
          git fetch --depth=1 origin develop

      - name: Set python version
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 #v5.4.0
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify Poetry version
        run: poetry --version

      - name: Check for Removed Rules
        run: |
          pipenv run make check-deprecated

      - name: Install dependencies
        run: poetry install
