on:
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'ECR image tag to use (default: panther-analysis-latest)'
        required: false
        default: 'panther-analysis-latest'

permissions:
  contents: read

jobs:
  test:
    if: github.event.pull_request.head.repo.fork == true
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout panther-analysis
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Set python version
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 #v5.4.0
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: pip install pipenv

      - name: Setup venv
        run: make venv

      - name: test
        run: |
          make data-models-unit-test global-helpers-unit-test
          pipenv run panther_analysis_tool test --show-failures-only

  login-to-ecr:
    if: github.event.pull_request.head.repo.fork == false
    name: Configure ECR Credentials
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          role-to-assume: arn:aws:iam::349240696275:role/DockerCI
          aws-region: us-west-2
          role-session-name: docker
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076
        with:
          # It is necessary to pass this in order for the password to be shared with the test job, 
          #   HOWEVER if does mean the passowrd may be printed if debug logging is enabled.
          mask-password: 'false'
    outputs:
      username: ${{ steps.login-ecr.outputs.docker_username_349240696275_dkr_ecr_us_west_2_amazonaws_com }}
      password: ${{ steps.login-ecr.outputs.docker_password_349240696275_dkr_ecr_us_west_2_amazonaws_com }}

  test-authenticated:
    if: github.event.pull_request.head.repo.fork == false
    name: Test
    needs: login-to-ecr
    runs-on: ubuntu-latest
    container:
      image: 349240696275.dkr.ecr.us-west-2.amazonaws.com/panther-community:${{ github.event.inputs.image_tag || 'panther-analysis-latest' }}
      credentials:
        username: ${{ needs.login-ecr.outputs.docker_username_349240696275_dkr_ecr_us_west_2_amazonaws_com }}
        password: ${{ needs.login-ecr.outputs.docker_password_349240696275_dkr_ecr_us_west_2_amazonaws_com }}
    env:
      API_HOST: ${{ secrets.API_HOST }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - name: Validate Secrets
        if: ${{ env.API_HOST == '' || env.API_TOKEN == '' }}
        run: |
          echo "API_HOST or API_TOKEN not set"
          exit 0
          
      - name: Checkout panther-analysis
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      # - name: Set python version
      #   uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 #v5.4.0
      #   with:
      #     python-version: "3.11"

      # - name: Install pipenv
      #   run: pip install pipenv

      # - name: Setup venv
      #   run: make venv

      - name: test
        run: |
          pipenv run panther_analysis_tool test --api-host ${{ env.API_HOST }} --api-token ${{ env.API_TOKEN }} --show-failures-only
